### ISSUE TITLE
Play next on items in history advances queue

### ISSUE THREAD

**Issue by deanputney** [nthall/watershed#6]
With Bandcamp items in my history, if I click "Play Next" an item gets added to my empty playlist, but not necessarily played. When I click "Play Next" on another item, it'll advance the list, add my item to the bottom, and play the first one. Then when I click "Play Next" a third time the queue advances and appends again. The end result is that I cannot re-queue more than two albums (one playing, one queued) at a time because the list keeps advancing.

**Comment by nthall** [comment]
I forgot there were issues on this project! This was resolved :)

**Comment by deanputney** [comment]
_From the graaaaave!_ 🧟‍♂️🧟‍♂️🧟‍♂️
